name: Build Spring Boot Application

trigger:
  branches:
    include:
      - master
      - dev
      - test

pr:
  - master

resources:
  repositories:
  - repository: pipelinetemplates # The name used to reference this repository in the checkout step
    type: github
    endpoint: 'vijaykumar-r'
    name: 'vijaykumar-r/azure_shared_components'
    ref: refs/heads/master

extends:
  template: pipeline_templates/pipeline_template.yml@pipelinetemplates
  parameters:
    projectName: 'Spring Boot App Gradle'
    workingDirectory: 'spring-boot-application-gradle'
    buildType: 'java'
    javaBuildTool: 'gradle'
    jdkVersion: '1.11'
    enableSmokeTest: true
    enableFunctionalTest: true
    javaOutputJarFile: 'build/libs/spring-boot-app.jar'
    sonarProjectKey: 'spring-boot-application-gradle'
    infraTerraformFolder: 'infrastructure'
    dockerFilePath: 'Dockerfile'

    beforeBuildSteps:
      - script: echo "MESSAGE FROM BEFORE BUILD STEPS"
        displayName: 'Pre build'
    afterBuildSteps:
      - script: echo "MESSAGE FROM AFTER BUILD STEPS"
        displayName: 'Post build'

    beforeBuildInfraSteps:
      - script: echo "MESSAGE FROM BEFORE INFRA BUILD STEPS"
        displayName: 'Pre Infra Build'
    afterBuildInfraSteps:
      - script: echo "MESSAGE FROM AFTER INFRA BUILD STEPS"
        displayName: 'Post Infra Build'

    beforeImageBuildSteps:
      - script: echo "MESSAGE FROM BEFORE IMAGE BUILD STEPS"
        displayName: 'Pre Image Build'
    afterImageBuildSteps:
      - script: echo "MESSAGE FROM AFTER IMAGE BUILD STEPS"
        displayName: 'Post Image Build'
