name: Build Spring Boot Application

trigger:
  branches:
    include:
      - master
      - dev
      - test

pr:
  - master

resources:
  repositories:
  - repository: pipelinelibrary # The name used to reference this repository in the checkout step. This name must be set to pipelinelibrary
    type: github
    endpoint: 'devops-toolschain'
    name: 'devops-toolschain/azure-pipeline-library'
    ref: refs/heads/master

extends:
  template: pipeline_templates/pipeline_template.yml@pipelinelibrary
  parameters:
    projectName: 'Spring Boot App Gradle'
    workingDirectory: 'spring-boot-application-gradle'
    buildType: 'java'
    javaBuildTool: 'gradle'
    jdkVersion: '1.11'
    javaOutputJarFile: 'build/libs/spring-boot-app.jar'
    sonarProjectKey: 'spring-boot-application-gradle'
    infraTerraformFolder: 'infrastructure'
    dockerFilePath: 'Dockerfile'
    chartName: 'spring-boot-application-gradle'
    chartPath: 'charts/spring-boot-application-gradle'

    beforeBuildSteps:
      - script: echo "MESSAGE FROM PRE BUILD STEPS"
        displayName: 'Pre build'
    afterBuildSteps:
      - script: echo "MESSAGE FROM POST BUILD STEPS"
        displayName: 'Post build'

    beforeBuildInfraSteps:
      - script: echo "MESSAGE FROM PRE INFRA BUILD STEPS"
        displayName: 'Pre Infra Build'
    afterBuildInfraSteps:
      - script: echo "MESSAGE FROM POST INFRA BUILD STEPS"
        displayName: 'Post Infra Build'

    beforeImageBuildSteps:
      - script: echo "MESSAGE FROM PRE IMAGE BUILD STEPS"
        displayName: 'Pre Image Build'
    afterImageBuildSteps:
      - script: echo "MESSAGE FROM POST IMAGE BUILD STEPS"
        displayName: 'Post Image Build'

    beforeSmokeTestSteps:
      - script: echo "MESSAGE FROM PRE SMOKE TEST STEPS"
        displayName: 'Pre Smoke Test'
    afterSmokeTestSteps:
      - script: echo "MESSAGE FROM POST SMOKE TEST STEPS"
        displayName: 'Post Smoke Test'

    beforeFunctionalTestSteps:
      - script: echo "MESSAGE FROM PRE FUNCTIONAL TEST STEPS"
        displayName: 'Pre Functional Test'
    afterFunctionalTestSteps:
      - script: echo "MESSAGE FROM POST FUNCTIONAL TEST STEPS"
        displayName: 'Post Functional Test'

    beforeHelmPublishSteps:
      - script: echo "MESSAGE FROM PRE HELM PUBLISH STEPS"
        displayName: 'Pre Functional Test'
    afterHelmPublishSteps:
      - script: echo "MESSAGE FROM POST HELM PUBLISH STEPS"
        displayName: 'Post Functional Test'
