name: Build Spring Boot Application

trigger:
  branches:
    include:
    - master
    - refs/pull/*

resources:
  repositories:
  - repository: pipelinetemplates # The name used to reference this repository in the checkout step
    type: github
    endpoint: 'vijaykumar-r'
    name: 'vijaykumar-r/azure_shared_components'
    ref: refs/heads/master

extends:
  template: pipeline_templates/azure_pipeline_template.yml@pipelinetemplates
  parameters:
    projectName: 'Spring Boot App Gradle'
    buildType: 'java'
    javaBuildTool: 'gradle'
    workingDirectory: 'spring-boot-application-gradle'
    sonarProjectKey: 'spring-boot-application-gradle'
    infraTerraformFolder: 'infrastructure'
    dockerOrgName: 'vijayace'
    checkOutSteps:
      - checkout: self
      - checkout: pipelinetemplates

    # sonarProjectKey: 'spring-boot-application'
    # beforeBuildSteps:
    #   - script: echo "FROM BEFORE BUILD STAGE"
    #     displayName: 'Pre build'
    # afterBuildSteps:
    #   - script: echo "FROM AFTER BUILD STAGE"
    #     displayName: 'Post build'
