name: Build Spring Boot Application

trigger: none
  # branches:
  #   include:
  #   - master
  #   - refs/pull/*

resources:
  repositories:
  - repository: pipelinetemplates # The name used to reference this repository in the checkout step
    type: github
    endpoint: 'vijaykumar-r'
    name: 'vijaykumar-r/azure_shared_components'
    ref: refs/heads/master

extends:
  template: pipeline_templates/pipeline_template.yml@pipelinetemplates
  parameters:
    agentPool: 'ubuntu-18.04'
    checkOutSteps:
      - checkout: self
      - checkout: pipelinetemplates
    projectName: 'Spring Boot App Gradle'
    workingDirectory: 'spring-boot-application-gradle'
    buildType: 'java'
    javaBuildTool: 'gradle'
    jdkVersion: '1.11'
    sonarProjectKey: 'spring-boot-application-gradle'
    buildInfrastructure: true
    infraTerraformFolder: 'infrastructure'
    buildDockerImage: true
    dockerFilePath: '/Dockerfile'

    # sonarProjectKey: 'spring-boot-application'
    # beforeJobSteps:
    #   - script: echo "FROM BEFORE BUILD STAGE"
    #     displayName: 'Pre build'
    # afterJobSteps:
    #   - script: echo "FROM AFTER BUILD STAGE"
    #     displayName: 'Post build'
